import type { Metadata } from "next";
import Link from "next/link";
import LegalPage from "@/components/legal-page";
import { LEGAL } from "@/lib/legal";
import { PLANS, PRICING } from "@/lib/billing";

export const metadata: Metadata = {
  title: "Terms of Service — Scoop",
  description: "The agreement that governs use of Scoop, the meeting recorder that assigns the work.",
};

export default function TermsPage() {
  const { productName: P, entityName, contactEmail, effectiveDate, governingLaw } = LEGAL;
  return (
    <LegalPage
      title="Terms of Service"
      effective={effectiveDate}
      intro={`These terms are a contract between ${entityName} and the company or person using ${P}. By creating a workspace, joining one, or letting Rocky into a meeting, you agree to them.`}
    >
      <section>
        <h2>1. The service</h2>
        <p>
          {P} joins your online meetings with a recording bot, transcribes them, and uses AI to produce summaries, decisions, tasks, owners, due dates and step-by-step guides, then delivers them to your team. We may add, change or retire features over time; we will not materially reduce the core service during a paid term without notice.
        </p>
      </section>

      <section>
        <h2>2. Accounts and workspaces</h2>
        <ul>
          <li>You must be at least 16 and able to enter a binding contract. If you use {P} for a company, you confirm you are authorized to bind it, and &ldquo;you&rdquo; means that company.</li>
          <li>A workspace is created by an admin, who can invite teammates, set recording policy, and manage billing. Admins are responsible for who they add and for what those users do.</li>
          <li>Keep your credentials confidential and tell us promptly at <a href={`mailto:${contactEmail}`}>{contactEmail}</a> if you suspect unauthorized access.</li>
        </ul>
      </section>

      <section>
        <h2>3. Recording and consent</h2>
        <p>
          You decide which meetings {P} records. You are responsible for complying with all laws that apply to recording, including obtaining consent from participants where required, and for telling participants that meetings are recorded and how their data is used. {P} announces itself as a participant and, by default, posts a recording notice in the meeting chat; do not disable those notices where the law requires them. You must not use {P} to record anyone who has asked not to be recorded.
        </p>
      </section>

      <section>
        <h2>4. Your content</h2>
        <ul>
          <li>You own your recordings, transcripts, summaries, tasks and everything else you put into or generate with {P} (&ldquo;Customer Content&rdquo;).</li>
          <li>You grant us a license to host, process, transmit and display Customer Content solely to provide and support the service, as described in our <Link href="/privacy">Privacy Policy</Link>. We do not use Customer Content to train AI models.</li>
          <li>You are responsible for Customer Content and confirm you have the rights and permissions needed to record and process it with {P}.</li>
        </ul>
      </section>

      <section>
        <h2>5. AI output</h2>
        <p>
          Summaries, tasks, owners, due dates and answers are generated by AI from the transcript. They can be incomplete or wrong, and captions provided by meeting platforms can mishear speakers. {P} links every item back to the recording so you can verify it, and offers a review mode that holds tasks for admin approval. You are responsible for checking AI output before relying on it, especially for legal, financial, medical or safety decisions.
        </p>
      </section>

      <section>
        <h2>6. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Record meetings unlawfully or without required consent, or record people who have objected.</li>
          <li>Upload or generate content that is illegal, infringing, or harmful, or that contains malware.</li>
          <li>Probe, disrupt or overload the service, bypass usage limits or billing, or access other customers&rsquo; data.</li>
          <li>Resell or white-label {P} without a written agreement, or use it to build a competing recording product.</li>
          <li>Use {P} in violation of the terms of Google, Microsoft, Zoom or any other platform it connects to.</li>
        </ul>
        <p>We may suspend or remove access to protect the service, other customers or the public, and will tell you why unless the law prevents it.</p>
      </section>

      <section>
        <h2>7. Plans, trials and payment</h2>
        <ul>
          <li><strong>Per-seat pricing.</strong> Subscriptions are priced per seat, where a seat is a team member who has joined the workspace. We offer {PLANS.map((p) => p.name).join(" and ")} plans, billed monthly or annually. Current prices are shown on our website and at checkout.</li>
          <li><strong>Seats update automatically.</strong> When a teammate joins or is removed, the seat count on your subscription changes and the difference is prorated on your next invoice.</li>
          <li><strong>Recording allowance.</strong> Each seat includes a number of recording hours per calendar month that depends on your plan ({PLANS.map((p) => `${p.name}: ${p.hoursPerSeat} hours`).join("; ")}), pooled across the workspace. Hours beyond the pool are billed at ${PRICING.overagePerHour.toFixed(2)} per hour, rounded up to the nearest hundredth of an hour, and invoiced on or about the first day of the following month to the payment method on file. Uploaded transcripts do not count.</li>
          <li><strong>Free trial.</strong> New workspaces get a {PRICING.trialDays}-day free trial that includes {PRICING.trialHours} recording hours. A payment method is required to start it. Unless you cancel before the trial ends, your subscription begins automatically and you will be charged for the plan you selected. One trial per company.</li>
          <li><strong>Renewal and cancellation.</strong> Plans renew automatically monthly or annually until cancelled. You can cancel any time from Settings → Billing; access continues until the end of the period you have paid for. Fees already paid are non-refundable except where the law requires otherwise or we say so in writing.</li>
          <li><strong>Failed payments.</strong> If a charge fails we will retry and notify your admins. If it remains unpaid, recording is paused; your summaries and tasks stay readable so you can export them.</li>
          <li><strong>Taxes.</strong> Prices exclude taxes. Where we must collect sales tax, VAT or similar, it is added at checkout.</li>
          <li><strong>Price changes.</strong> We may change prices with at least 30 days&rsquo; notice by email; changes apply from your next renewal after the notice period. Annual plans keep their price until renewal.</li>
          <li>Payments are processed by Stripe under its own terms. We never see your full card number.</li>
        </ul>
      </section>

      <section>
        <h2>8. Data, retention and export</h2>
        <p>
          Your admins control how long recordings and transcripts are kept (the default for new workspaces is {PRICING.defaultRetentionDays} days) and can export the whole workspace as JSON at any time. Our handling of personal data is described in the <Link href="/privacy">Privacy Policy</Link>, which forms part of these terms. If you need a data processing agreement, contact us.
        </p>
      </section>

      <section>
        <h2>9. Our property</h2>
        <p>{P}, Rocky, our software, design and documentation belong to {entityName} and our licensors and are protected by intellectual property laws. These terms do not give you any rights in them beyond using the service. Feedback you send us may be used without obligation to you.</p>
      </section>

      <section>
        <h2>10. Third-party services</h2>
        <p>{P} connects to Google, Microsoft, Zoom, Slack and other services you choose. Those services are governed by their own terms and availability, and we are not responsible for changes they make, for example a platform disabling captions or bot participants.</p>
      </section>

      <section>
        <h2>11. Termination</h2>
        <p>
          You can stop using {P} and delete your workspace at any time. We may suspend or terminate your access if you materially breach these terms and do not fix the breach within 10 days of notice, if you do not pay, or if we are required to by law. On termination your right to use the service ends; you can export your data beforehand, and we delete Customer Content in line with the Privacy Policy. Sections 4, 5, 9 and 12 to 16 survive termination.
        </p>
      </section>

      <section>
        <h2>12. Warranties and disclaimers</h2>
        <p>
          We will provide {P} with reasonable skill and care. Otherwise, to the fullest extent permitted by law, the service is provided <strong>&ldquo;as is&rdquo;</strong> without warranties of any kind, express or implied, including fitness for a particular purpose, accuracy of transcripts or AI output, and uninterrupted or error-free operation. Meetings may fail to record for reasons outside our control, such as a platform blocking the bot, a host declining it, or captions being unavailable.
        </p>
      </section>

      <section>
        <h2>13. Limitation of liability</h2>
        <p>
          To the fullest extent permitted by law, neither party is liable for indirect, incidental, special, consequential or punitive damages, or for lost profits, revenue, data or goodwill, arising from these terms or the service, even if advised of the possibility. Our total liability for all claims in any 12-month period is limited to the amount you paid us for the service in that period. These limits do not apply to your payment obligations, either party&rsquo;s indemnity obligations, or liability that cannot be limited by law.
        </p>
      </section>

      <section>
        <h2>14. Indemnity</h2>
        <p>You will defend and indemnify {entityName} against third-party claims arising from Customer Content, from recording without required consent, or from your breach of these terms. We will defend and indemnify you against third-party claims that the service, as provided by us, infringes their intellectual property rights.</p>
      </section>

      <section>
        <h2>15. Governing law and disputes</h2>
        <p>
          These terms are governed by {governingLaw}, without regard to conflict-of-law rules. Before starting any formal proceeding, each party agrees to try to resolve the dispute by contacting the other and negotiating in good faith for 30 days. Nothing here limits either party from seeking injunctive relief or prevents consumers from relying on mandatory protections of their home jurisdiction.
        </p>
      </section>

      <section>
        <h2>16. General</h2>
        <ul>
          <li>These terms, the Privacy Policy and any order or plan you select are the entire agreement between us about {P}.</li>
          <li>If any part is unenforceable, the rest remains in effect. Failure to enforce a right is not a waiver.</li>
          <li>You may not assign these terms without our consent, except to a successor in a merger or sale of your business. We may assign them to an affiliate or successor.</li>
          <li>We may update these terms. For material changes we will notify workspace admins by email at least 30 days before they take effect; continuing to use {P} after that means you accept the new terms.</li>
          <li>Notices to us go to <a href={`mailto:${contactEmail}`}>{contactEmail}</a>. Notices to you go to your admins&rsquo; email addresses on file.</li>
        </ul>
      </section>
    </LegalPage>
  );
}
