// Scans public/mascot for pose images and writes src/generated/mascot-images.ts.
// Run automatically before build (and via `npm run mascot:sync`).
import { readdirSync, mkdirSync, writeFileSync, existsSync } from "node:fs";

const POSES = ["wave", "listen", "think", "celebrate", "sleep", "write", "alert"];
const EXTS = ["png", "webp", "svg"];
const dir = "public/mascot";
const found = {};
if (existsSync(dir)) {
  const files = new Set(readdirSync(dir));
  for (const pose of POSES) {
    for (const ext of EXTS) {
      if (files.has(`${pose}.${ext}`)) { found[pose] = `/mascot/${pose}.${ext}`; break; }
    }
  }
}
mkdirSync("src/generated", { recursive: true });
writeFileSync(
  "src/generated/mascot-images.ts",
  `// Generated by scripts/sync-mascot.mjs — do not edit. Drop images into public/mascot/<pose>.png and rebuild.\nexport const MASCOT_IMAGES: Record<string, string> = ${JSON.stringify(found, null, 2)};\n`,
);
console.log(`mascot images: ${Object.keys(found).length ? Object.keys(found).join(", ") : "none (using built-in SVG)"}`);
